title: SAVANT.SPECTER
description: >- # ignore
  Possibly interesting data analytics
baseurl: ""
url: "savantspecter.github.io"
twitter_username: SavantSpecter
github_username: savantspecter

#Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
